version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: aws-serverless-deployment-with-SAM
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity 
